### ISSUE TITLE
Request: RISC-V GCC 10.1 including g++

### ISSUE THREAD

**Issue by tcal-x** [hdl/conda-compilers#25]
We'd like to use Conda to get the RISCV GCC toolchain in CFU Playground.   Because we're compiling TFLite for Microprocessors, we need to compile C++, so we need g++.    We saw significant speedup using GCC 10.1 over 8.3 (https://github.com/google/CFU-Playground/issues/182), so we're requesting that version -- 10.1.  

Currently we use a manual installation of [SiFive Freedom Tools v2020.08.0](https://github.com/sifive/freedom-tools/releases/tag/v2020.08.0), and it is known to work.   So if there are any questions about which version of newlib or binutils, use those (3.2 and 2.35 respectively).

**Comment by mithro** [comment]
@PiotrZierhoffer Can you get someone to look into this?

**Comment by kgugala** [comment]
@tcal-x I also couldn't find a risc-v toolchain with C++ support in conda. We'll add a recipe for that so we can have one

**Comment by PiotrZierhoffer** [comment]
I'll verify https://anaconda.org/LiteX-Hub/gcc-riscv32-elf-newlib/files and we'll see if it can be easily bumped

**Comment by PiotrZierhoffer** [comment]
Right now we have binutils 2.34 and newlib 3.3. Let's start with those and see what happens

**Comment by PiotrZierhoffer** [comment]
Should be done when the CI passes

**Comment by tcal-x** [comment]
Thanks @PiotrZierhoffer @kgugala !
